name: mercari
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - nltk
  - flask
  - re
  - pickle

#  - pip:
#      - pip package 1
#      - pip package 2
